### ISSUE TITLE
Please add All export

### ISSUE THREAD

**Issue by tblion** [mtolly/jammittools#5]
Hi, Thank you for you work... It's very cool.

Can you add an "all" export ? I don't know Haskell so I can't do it.

Jammit is "dead", the ipad App is dead and I want to export all my songs before the PC apps dead too...

Thank you :)

**Comment by mtolly** [comment]
Yeah, I'd be happy to do so!

I had no idea all the apps were broken, that's a shame :( I haven't opened my Mac app in a while but it now says I have no internet connection... Glad I downloaded everything.

**Comment by mtolly** [comment]
I've added a `-b <dir>` option that does this in a new release:
https://github.com/mtolly/jammittools/releases/tag/v0.5.1

Let me know if it works for you!

**Comment by tblion** [comment]
Thanks guy, it's amazing :)
